import React,{useEffect,useState} from 'react';
import {Bot,Send,RefreshCw,ShieldCheck,ClipboardCheck,Check,X,FileText,AlertTriangle,Trash2} from 'lucide-react';

// Deliberately no raw HTML, model-generated links, remote images, or executable Markdown.
function Markdown({text}){
  const lines=String(text||'').split('\n'),blocks=[];
  for(let i=0;i<lines.length;i++){
    if(lines[i].trim().startsWith('|')&&lines[i+1]?.match(/^\s*\|[\s:|\-]+\|\s*$/)){
      const cells=line=>line.trim().replace(/^\||\|$/g,'').split('|').map(x=>x.trim().replace(/\*\*/g,''));
      const headers=cells(lines[i]);const rows=[];i+=2;
      while(i<lines.length&&lines[i].trim().startsWith('|')){rows.push(cells(lines[i]));i++}i--;
      blocks.push(<div className="table-scroll" key={i}><table><thead><tr>{headers.map((h,n)=><th key={n}>{h}</th>)}</tr></thead><tbody>{rows.map((r,n)=><tr key={n}>{r.map((c,k)=><td key={k}>{c}</td>)}</tr>)}</tbody></table></div>);
    }else if(/^#{1,3} /.test(lines[i]))blocks.push(<h4 key={i}>{lines[i].replace(/^#{1,3} /,'')}</h4>);
    else if(lines[i].trim())blocks.push(<p key={i}>{lines[i]}</p>);
  }
  return <div className="ai-markdown">{blocks}</div>;
}
function Values({value}){
  if(Array.isArray(value))return <div className="ai-value-list">{value.map((v,i)=><div key={i}><Values value={v}/></div>)}</div>;
  if(value&&typeof value==='object')return <dl className="ai-values">{Object.entries(value).map(([k,v])=><React.Fragment key={k}><dt>{k.replaceAll('_',' ')}</dt><dd><Values value={v}/></dd></React.Fragment>)}</dl>;
  return <span>{typeof value==='boolean'?(value?'Yes':'No'):String(value??'—')}</span>;
}
export default function AgentWorkspace({api,onChanged}){
  const[status,setStatus]=useState(null),[messages,setMessages]=useState([]),[conversation,setConversation]=useState(null),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[drafts,setDrafts]=useState([]),[audit,setAudit]=useState({events:[],content_flags:[]}),[tab,setTab]=useState('chat'),[review,setReview]=useState(null),[confirmed,setConfirmed]=useState(false),[saving,setSaving]=useState(false);
  async function load(){try{const [s,d,a]=await Promise.all([api('ai/status/'),api('ai/drafts/'),api('ai/audit/')]);setStatus(s);setDrafts(d);setAudit(a)}catch(e){setError(e.message)}}
  useEffect(()=>{load()},[]);
  async function send(e){e.preventDefault();if(!input.trim()||busy)return;const message=input.trim();setInput('');setError('');setBusy(true);setMessages(m=>[...m,{role:'user',text:message}]);
    try{const r=await api('ai/chat/',{message,...(conversation?{conversation_id:conversation}:{})});setConversation(r.conversation_id);setMessages(m=>[...m,{role:'assistant',text:r.answer,tools:r.tools,reports:r.reports,references:r.references,drafts:r.draft_ids,alerts:r.alerts}]);}
    catch(e){setError(e.message)}finally{setBusy(false);await load()}}
  async function clear(){if(busy)return;try{await api('ai/conversations/clear/',{});setMessages([]);setConversation(null);setError('')}catch(e){setError(e.message)}}
  async function decide(decision){if(!confirmed||!review)return;setSaving(true);setError('');try{await api(`ai/drafts/${review.id}/review/`,{decision,confirmed:true,review_token:review.review_token});setReview(null);setConfirmed(false);await load();await onChanged()}catch(e){setError(e.message)}finally{setSaving(false)}}
  const pending=drafts.filter(d=>d.status==='pending');
  return <div className="ai-workspace"><div className="ai-status"><div className="ai-status-icon"><Bot size={24}/></div><div><b>Clinical & administrative agent</b><small>{status?.provider||'Ollama · local only'} · {status?.model||'Checking model'} · {status?.scope||'Checking access'}</small></div><span className={'badge '+(status?.ready?'':'warning')}>{status?.ready?'Model available':'Setup required'}</span><button className="secondary" onClick={load} aria-label="Refresh AI status"><RefreshCw size={15}/></button></div>
    <div className="ai-boundary"><ShieldCheck size={17}/><span>Doctors and admins only. Database tools are restricted. Prescriptions and payments require the assigned doctor's review click. AI content is unverified.</span></div>
    {!status?.ready&&<div className="panel ai-setup"><h3>Run a free local model</h3><p>{status?.detail||'Checking local Ollama connection…'}</p><code>ollama pull {status?.model||'qwen3:8b'}</code><p>Start the Ollama desktop app, then refresh status. No API key is needed. For less memory, use qwen3:4b and set OLLAMA_MODEL in your Django terminal before restarting Django.</p></div>}
    <div className="ai-tabs">{[['chat','Chat'],['drafts',`Review queue (${pending.length})`],['audit','Activity & flags']].map(([id,label])=><button key={id} className={tab===id?'selected':''} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {error&&<div className="error" role="alert">{error}</div>}
    {tab==='chat'&&<div className="panel ai-chat"><div className="ai-chat-top"><span><Bot size={17}/> Local clinical workspace</span><button className="text-button" disabled={busy} onClick={clear}><Trash2 size={14}/> Clear stored chats</button></div><div className="ai-messages" aria-live="polite">
      {!messages.length&&<div className="ai-empty"><Bot size={36}/><h3>Query records. Review evidence. Approve deliberately.</h3><p>Specify patient references, drug quantities, and exact reporting dates.</p><div className="ai-examples">{['Show current drug stock and flag low inventory.','Show revenue for this month.','List available doctors and medical services.'].map(text=><button key={text} onClick={()=>setInput(text)}>{text}</button>)}</div></div>}
      {messages.map((m,i)=><article className={'ai-message '+m.role} key={i}><small>{m.role==='user'?'YOUR REQUEST':'AI DRAFT RESPONSE · VERIFY BEFORE USE'}</small><Markdown text={m.text}/>{m.alerts?.map((a,k)=><div className="ai-stock-alert" role="alert" key={k}><b>{a.message}</b><Values value={a.inventory}/></div>)}{m.tools?.length>0&&<details><summary>Database tools ({m.tools.length})</summary>{m.tools.map((t,k)=><p key={k}>{t.tool.replaceAll('_',' ')} · {t.status}</p>)}</details>}{m.reports?.map((r,k)=><div className="ai-report" key={k}><small>VERIFIED DATABASE TOTALS</small><Markdown text={r}/></div>)}{m.references?.map((r,k)=><a key={k} className="secondary prescription-pdf" href={`/api/ai/prescriptions/${Number(r.id)}/pdf/`} target="_blank" rel="noopener noreferrer"><FileText size={15}/>{r.label}</a>)}{m.drafts?.length>0&&<button className="secondary" onClick={()=>{setTab('drafts');load()}}><ClipboardCheck size={15}/> Review {m.drafts.length} pending proposal(s)</button>}</article>)}
      {busy&&<div className="ai-thinking"><span className="live-dot"/> Local model is processing. Larger models may take several minutes on a CPU.</div>}
    </div><form className="ai-compose" onSubmit={send}><label htmlFor="ai-message">Clinical / administrative request</label><textarea id="ai-message" value={input} onChange={e=>setInput(e.target.value)} maxLength={4000} rows={3} placeholder="Example: Show revenue from 2026-09-01 to 2026-09-30" disabled={busy}/><div><small>Chat history stays in the clinic database until cleared. Never enter credentials.</small><button className="primary" disabled={busy||!status?.ready||!input.trim()}><Send size={16}/>{busy?'Processing…':'Send request'}</button></div></form></div>}
    {tab==='drafts'&&<div className="ai-drafts">{!drafts.length&&<div className="panel empty">No AI proposals. Ask the agent to prepare a draft with the required details.</div>}{drafts.map(d=><article className="panel ai-draft" key={d.id}><div><span className="eyebrow">PROPOSAL #{d.id}</span><h3>{d.kind.replaceAll('_',' ')}</h3><p>{d.review.patient||d.review.drug||d.review.doctor||'Administrative change'}</p><small>{d.approval_rule}</small></div><div><span className={'badge '+(d.status==='pending'?'warning':'')}>{d.status}</span>{d.can_approve?<button className="secondary" onClick={()=>{setReview(d);setConfirmed(false);setError('')}}><ClipboardCheck size={16}/> Review exact change</button>:d.status==='pending'?<small>Awaiting designated reviewer or expired.</small>:null}{d.status==='approved'&&d.kind==='prescription'&&<a className="text-button" href={`/api/ai/prescriptions/${d.result_id}/pdf/`} target="_blank" rel="noopener noreferrer">Print patient copy</a>}</div></article>)}</div>}
    {tab==='audit'&&<div className="panel ai-audit"><h3>Agent activity</h3><p>Tool names and outcomes only. Arguments and clinical content are excluded from this log.</p><div className="table-scroll"><table><thead><tr><th>Time</th><th>Action</th><th>Outcome</th><th>Proposal</th></tr></thead><tbody>{audit.events.map(e=><tr key={e.id}><td>{new Date(e.created_at).toLocaleString()}</td><td>{e.action}</td><td>{e.outcome}</td><td>{e.draft_id||'—'}</td></tr>)}</tbody></table></div><h3>Human-reviewed community flags</h3>{audit.content_flags.length?audit.content_flags.map(f=><p key={f.id}>Post #{f.post_id}: {f.reason}</p>):<p>No reviewed flags available in your scope.</p>}</div>}
    {review&&<div className="modal-backdrop"><section className="modal ai-review" role="dialog" aria-modal="true" aria-labelledby="ai-review-title"><div className="modal-heading"><div><div className="eyebrow">HUMAN REVIEW REQUIRED</div><h2 id="ai-review-title">Review {review.kind.replaceAll('_',' ')} #{review.id}</h2></div><button aria-label="Close review" disabled={saving} onClick={()=>setReview(null)}><X/></button></div><div className="ai-boundary"><AlertTriangle size={20}/><span>{review.approval_rule} Approving a prescription dispenses stock immediately. Approving a payment records a received amount.</span></div><h3>Exact proposed record</h3><Values value={review.payload}/><h3>Verification at drafting time</h3><Values value={review.review}/>{error&&<div className="error" role="alert">{error}</div>}<label className="ai-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I have personally reviewed this exact record, patient identity, and all clinical or financial details. I am the authorized reviewer.</label><div className="modal-actions"><button className="secondary" disabled={saving||!confirmed} onClick={()=>decide('reject')}><X size={16}/> Reject proposal</button><button className="primary" disabled={saving||!confirmed} onClick={()=>decide('approve')}><Check size={16}/>{saving?'Saving…':'Approve and save'}</button></div></section></div>}
  </div>;
}
